// DBC Challenge 7.1
// JavaScript Reverse String Function

// PSEUDOCODE:
// Define Function reverse_string
//   This function takes a string as an argument and returns a reversed string.

// Assign variable with an empty string to hold the reversed string

// Use a for while loop to iterate through input string
//   Since the characters in the string can be accessed via their index values,
//   the loop will start at the end of the index string and iterate towards
//   the beginning.
//   As each character is accessed, it will be concatenated onto the 
//   return string variable.

// Explicity return the reversed string variable

// IMPLEMENTED CODE:
function reverse_string(phrase) {
  var reversed_string = '';

  for (idx = phrase.length - 1; idx >= 0; idx -= 1) {
    reversed_string += phrase[idx]
  }
  return reversed_string
}

// Driver Code
mixed_veggie = reverse_string("eggplant")


flip = Math.floor(Math.random() * 2) // Generate a random number that is 0 or 1
 
// Only print the reversed string if a 1 was generated by the RNG
if (flip == 0) {
  console.log("Sorry, I will print the reversed string this time.");
} else if (flip == 1) {
  console.log("If you reverse 'eggplant', the reversed string is '" 
              + mixed_veggie + "'.");
} else {
  console.log("Your Random Number Generator isn't returning 0 or 1!!!");
}

